name: Utils
main: snerble.minecraft.plugins.utils.UtilsPlugin
description: Contains random garbage lmao.
version: 3.2.1
api-version: 1.13

permissions:
   utils.op:
      default: op
   utils.not_op:
      default: not op
   utils.all:
      default: true
   utils.none:
      default: false

commands:
   daytime:
      permission: utils.all
      description: Advances time to the next morning.
   autoTorch:
      permission: utils.all
      description: Automatically places torches when it gets too dark.
   spawn:
      permission: utils.all
      description: Teleports the player to a spawn point.
   setcolor:
      permission: utils.op
      description: Sets the color of the plugin prefix in the chat.
   tc:
      permission: utils.all
      description: Command for managing the TreeCutter system.
   autoCraft:
      permission: utils.all
      description: Command for managing the AutoCraft system.
   slimeChunks:
      permissions: utils.all
      description: Lists all nearby slime chunks within a certain radius.
   xpMult:
      permission: utils.op
      description: Sets the modifier applied to all xp picked up by players.